# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\"0\n\nSensorData\x12\x13\n\x0bsensor_type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty25\n\rSensorService\x12$\n\rGetSensorData\x12\x06.Empty\x1a\x0b.SensorDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SENSORDATA']._serialized_start=16
  _globals['_SENSORDATA']._serialized_end=64
  _globals['_EMPTY']._serialized_start=66
  _globals['_EMPTY']._serialized_end=73
  _globals['_SENSORSERVICE']._serialized_start=75
  _globals['_SENSORSERVICE']._serialized_end=128
# @@protoc_insertion_point(module_scope)
