serial:
  port: "/dev/pts/12"
  baudrate: 9600
  timeout: 5
  delay: 1

sensors:
  Temperature:
    min_value: 15
    max_value: 45
    unit: "°C"
  Pressure:
    min_value: 980
    max_value: 1020
    unit: "hPa"
  Water Level:
    min_value: 1
    max_value: 5
    unit: "meters"
